-- AlterTable
ALTER TABLE `Car` MODIFY `status` ENUM('AVAILABLE', 'IN_USE', 'IN_REPAIR') NOT NULL DEFAULT 'AVAILABLE';

-- AlterTable
ALTER TABLE `Event` MODIFY `eventType` ENUM('CHECKOUT', 'RETURN', 'REPAIR', 'REPAIR_RETURN') NOT NULL;

-- AlterTable
ALTER TABLE `Report` MODIFY `eventType` ENUM('CHECKOUT', 'RETURN', 'REPAIR', 'REPAIR_RETURN') NOT NULL;
